### ISSUE TITLE
MongoDB Atlas Support?

### ISSUE THREAD

**Issue by cryptoquick** [GoogleCloudPlatform/mongodb-cloud-manager#1]
When I try to log in to the MongoDB Cloud Manager console, I'm brought to their new interface. Trying to follow this instruction:

`Navigate to Cloud Manager > Settings > Group Settings and copy the Group ID and Agent API Key at the top of the page, you will need these values below`

The Agent API Key is not available on this page. I tried to enable API access and generate a key, but when used with your script, I found an error by digging into the syslog on one of the servers:

`mmsApiKey can only consist of alphanumeric characters`

Not sure where to go from here.

Also, do I need to use MongoDB's API Whitelist in any way in order for any of these operations to work?

**Comment by cryptoquick** [comment]
Hey, we're still looking to use MongoDB on GCP assisted with MongoDB Atlas or similar. Can any help be provided with regards to the original ticket? @crcsmnky

**Comment by crcsmnky** [comment]
Hi @cryptoquick, sorry for the delay in responding. This will be a bit long winded because their interface is a bit strange. 

If you go to `Cloud Manager` > `Settings` > `Group Settings` and only see the `Group ID` then the group you are in is only for MongoDB Atlas. Either select another group with Cloud Manager from the MongoDB Cloud Manager menu bar and drop-down at the top, or create a new group entirely for Cloud Manager. 

To create a new group go to `Settings` > `My Groups` and click on `Add Group` in the upper right. Then you can create one specifically for Cloud Manager (as opposed to Atlas). Once created, the `Group Settings` page will have the `Group ID` and `Agent API Key` at the top of the page.

**Comment by cryptoquick** [comment]
Ah, okay! That wasn't immediately obvious. 👍 
Got it running, thanks!
